'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.WebService1Soap")>  _
    Public Interface WebService1Soap
        
        'CODEGEN: Generating message contract since the wrapper name (List_x0020_Student) of message List_x0020_Student does not match the default value (getStudentData)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/List Student", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getStudentData(ByVal request As ServiceReference1.ListStudent) As ServiceReference1.ListStudent1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/List Student", ReplyAction:="*")>  _
        Function getStudentDataAsync(ByVal request As ServiceReference1.ListStudent) As System.Threading.Tasks.Task(Of ServiceReference1.ListStudent1)
        
        'CODEGEN: Generating message contract since the wrapper name (Add_x0020_Student) of message Add_x0020_Student does not match the default value (addStudent)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Add Student", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function addStudent(ByVal request As ServiceReference1.AddStudent) As ServiceReference1.AddStudent1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Add Student", ReplyAction:="*")>  _
        Function addStudentAsync(ByVal request As ServiceReference1.AddStudent) As System.Threading.Tasks.Task(Of ServiceReference1.AddStudent1)
        
        'CODEGEN: Generating message contract since the wrapper name (Delete_x0020_Student) of message Delete_x0020_Student does not match the default value (deleteStudent)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Delete Student", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function deleteStudent(ByVal request As ServiceReference1.DeleteStudent) As ServiceReference1.DeleteStudent1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Delete Student", ReplyAction:="*")>  _
        Function deleteStudentAsync(ByVal request As ServiceReference1.DeleteStudent) As System.Threading.Tasks.Task(Of ServiceReference1.DeleteStudent1)
        
        'CODEGEN: Generating message contract since the wrapper name (List_x0020_Course) of message List_x0020_Course does not match the default value (listCourse)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/List Course", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function listCourse(ByVal request As ServiceReference1.ListCourse) As ServiceReference1.ListCourse1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/List Course", ReplyAction:="*")>  _
        Function listCourseAsync(ByVal request As ServiceReference1.ListCourse) As System.Threading.Tasks.Task(Of ServiceReference1.ListCourse1)
        
        'CODEGEN: Generating message contract since the wrapper name (Get_x0020_Course_x0020_Registered_x0020_Students) of message Get_x0020_Course_x0020_Registered_x0020_Students does not match the default value (getCourseRegisteredStudents)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Get Course Registered Students", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getCourseRegisteredStudents(ByVal request As ServiceReference1.GetCourseRegisteredStudents) As ServiceReference1.GetCourseRegisteredStudents1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Get Course Registered Students", ReplyAction:="*")>  _
        Function getCourseRegisteredStudentsAsync(ByVal request As ServiceReference1.GetCourseRegisteredStudents) As System.Threading.Tasks.Task(Of ServiceReference1.GetCourseRegisteredStudents1)
        
        'CODEGEN: Generating message contract since the wrapper name (Register_x0020_course) of message Register_x0020_course does not match the default value (registerNewCourse)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Register course", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function registerNewCourse(ByVal request As ServiceReference1.Registercourse) As ServiceReference1.Registercourse1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Register course", ReplyAction:="*")>  _
        Function registerNewCourseAsync(ByVal request As ServiceReference1.Registercourse) As System.Threading.Tasks.Task(Of ServiceReference1.Registercourse1)
        
        'CODEGEN: Generating message contract since the wrapper name (Get_x0020_all_x0020_registered_x0020_courses) of message Get_x0020_all_x0020_registered_x0020_courses does not match the default value (getAllRegisteredCourses)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Get all registered courses", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getAllRegisteredCourses(ByVal request As ServiceReference1.Getallregisteredcourses) As ServiceReference1.Getallregisteredcourses1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Get all registered courses", ReplyAction:="*")>  _
        Function getAllRegisteredCoursesAsync(ByVal request As ServiceReference1.Getallregisteredcourses) As System.Threading.Tasks.Task(Of ServiceReference1.Getallregisteredcourses1)
        
        'CODEGEN: Generating message contract since the wrapper name (email_x0020_test) of message email_x0020_test does not match the default value (emailTest)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/email test", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function emailTest(ByVal request As ServiceReference1.emailtest) As ServiceReference1.emailtest1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/email test", ReplyAction:="*")>  _
        Function emailTestAsync(ByVal request As ServiceReference1.emailtest) As System.Threading.Tasks.Task(Of ServiceReference1.emailtest1)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="List Student", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class ListStudent
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="List StudentResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class ListStudent1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute("List StudentResult")>  _
        Public ListStudentResult As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ListStudentResult As System.Data.DataSet)
            MyBase.New
            Me.ListStudentResult = ListStudentResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Add Student", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class AddStudent
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public id As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public name As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public type As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal id As String, ByVal name As String, ByVal type As String)
            MyBase.New
            Me.id = id
            Me.name = name
            Me.type = type
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Add StudentResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class AddStudent1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute("Add StudentResult")>  _
        Public AddStudentResult As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AddStudentResult As System.Data.DataSet)
            MyBase.New
            Me.AddStudentResult = AddStudentResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Delete Student", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class DeleteStudent
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public id As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal id As String)
            MyBase.New
            Me.id = id
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Delete StudentResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class DeleteStudent1
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="List Course", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class ListCourse
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="List CourseResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class ListCourse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute("List CourseResult")>  _
        Public ListCourseResult As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ListCourseResult As System.Data.DataSet)
            MyBase.New
            Me.ListCourseResult = ListCourseResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Get Course Registered Students", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetCourseRegisteredStudents
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public id As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal id As String)
            MyBase.New
            Me.id = id
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Get Course Registered StudentsResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetCourseRegisteredStudents1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute("Get Course Registered StudentsResult")>  _
        Public GetCourseRegisteredStudentsResult As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetCourseRegisteredStudentsResult As System.Data.DataSet)
            MyBase.New
            Me.GetCourseRegisteredStudentsResult = GetCourseRegisteredStudentsResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Register course", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class Registercourse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public s_id As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public s_name As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public c_id As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=3)>  _
        Public c_title As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=4)>  _
        Public c_w_hours As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal s_id As String, ByVal s_name As String, ByVal c_id As String, ByVal c_title As String, ByVal c_w_hours As String)
            MyBase.New
            Me.s_id = s_id
            Me.s_name = s_name
            Me.c_id = c_id
            Me.c_title = c_title
            Me.c_w_hours = c_w_hours
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Register courseResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class Registercourse1
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Get all registered courses", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class Getallregisteredcourses
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public id As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal id As String)
            MyBase.New
            Me.id = id
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Get all registered coursesResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class Getallregisteredcourses1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute("Get all registered coursesResult")>  _
        Public GetallregisteredcoursesResult As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetallregisteredcoursesResult As System.Data.DataSet)
            MyBase.New
            Me.GetallregisteredcoursesResult = GetallregisteredcoursesResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="email test", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class emailtest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="email testResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class emailtest1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute("email testResult")>  _
        Public emailtestResult As System.Data.DataSet
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal emailtestResult As System.Data.DataSet)
            MyBase.New
            Me.emailtestResult = emailtestResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WebService1SoapChannel
        Inherits ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebService1SoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.WebService1Soap)
        Implements ServiceReference1.WebService1Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_WebService1Soap_getStudentData(ByVal request As ServiceReference1.ListStudent) As ServiceReference1.ListStudent1 Implements ServiceReference1.WebService1Soap.getStudentData
            Return MyBase.Channel.getStudentData(request)
        End Function
        
        Public Function getStudentData() As System.Data.DataSet
            Dim inValue As ServiceReference1.ListStudent = New ServiceReference1.ListStudent()
            Dim retVal As ServiceReference1.ListStudent1 = CType(Me,ServiceReference1.WebService1Soap).getStudentData(inValue)
            Return retVal.ListStudentResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_WebService1Soap_getStudentDataAsync(ByVal request As ServiceReference1.ListStudent) As System.Threading.Tasks.Task(Of ServiceReference1.ListStudent1) Implements ServiceReference1.WebService1Soap.getStudentDataAsync
            Return MyBase.Channel.getStudentDataAsync(request)
        End Function
        
        Public Function getStudentDataAsync() As System.Threading.Tasks.Task(Of ServiceReference1.ListStudent1)
            Dim inValue As ServiceReference1.ListStudent = New ServiceReference1.ListStudent()
            Return CType(Me,ServiceReference1.WebService1Soap).getStudentDataAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_WebService1Soap_addStudent(ByVal request As ServiceReference1.AddStudent) As ServiceReference1.AddStudent1 Implements ServiceReference1.WebService1Soap.addStudent
            Return MyBase.Channel.addStudent(request)
        End Function
        
        Public Function addStudent(ByVal id As String, ByVal name As String, ByVal type As String) As System.Data.DataSet
            Dim inValue As ServiceReference1.AddStudent = New ServiceReference1.AddStudent()
            inValue.id = id
            inValue.name = name
            inValue.type = type
            Dim retVal As ServiceReference1.AddStudent1 = CType(Me,ServiceReference1.WebService1Soap).addStudent(inValue)
            Return retVal.AddStudentResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_WebService1Soap_addStudentAsync(ByVal request As ServiceReference1.AddStudent) As System.Threading.Tasks.Task(Of ServiceReference1.AddStudent1) Implements ServiceReference1.WebService1Soap.addStudentAsync
            Return MyBase.Channel.addStudentAsync(request)
        End Function
        
        Public Function addStudentAsync(ByVal id As String, ByVal name As String, ByVal type As String) As System.Threading.Tasks.Task(Of ServiceReference1.AddStudent1)
            Dim inValue As ServiceReference1.AddStudent = New ServiceReference1.AddStudent()
            inValue.id = id
            inValue.name = name
            inValue.type = type
            Return CType(Me,ServiceReference1.WebService1Soap).addStudentAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_WebService1Soap_deleteStudent(ByVal request As ServiceReference1.DeleteStudent) As ServiceReference1.DeleteStudent1 Implements ServiceReference1.WebService1Soap.deleteStudent
            Return MyBase.Channel.deleteStudent(request)
        End Function
        
        Public Sub deleteStudent(ByVal id As String)
            Dim inValue As ServiceReference1.DeleteStudent = New ServiceReference1.DeleteStudent()
            inValue.id = id
            Dim retVal As ServiceReference1.DeleteStudent1 = CType(Me,ServiceReference1.WebService1Soap).deleteStudent(inValue)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_WebService1Soap_deleteStudentAsync(ByVal request As ServiceReference1.DeleteStudent) As System.Threading.Tasks.Task(Of ServiceReference1.DeleteStudent1) Implements ServiceReference1.WebService1Soap.deleteStudentAsync
            Return MyBase.Channel.deleteStudentAsync(request)
        End Function
        
        Public Function deleteStudentAsync(ByVal id As String) As System.Threading.Tasks.Task(Of ServiceReference1.DeleteStudent1)
            Dim inValue As ServiceReference1.DeleteStudent = New ServiceReference1.DeleteStudent()
            inValue.id = id
            Return CType(Me,ServiceReference1.WebService1Soap).deleteStudentAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_WebService1Soap_listCourse(ByVal request As ServiceReference1.ListCourse) As ServiceReference1.ListCourse1 Implements ServiceReference1.WebService1Soap.listCourse
            Return MyBase.Channel.listCourse(request)
        End Function
        
        Public Function listCourse() As System.Data.DataSet
            Dim inValue As ServiceReference1.ListCourse = New ServiceReference1.ListCourse()
            Dim retVal As ServiceReference1.ListCourse1 = CType(Me,ServiceReference1.WebService1Soap).listCourse(inValue)
            Return retVal.ListCourseResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_WebService1Soap_listCourseAsync(ByVal request As ServiceReference1.ListCourse) As System.Threading.Tasks.Task(Of ServiceReference1.ListCourse1) Implements ServiceReference1.WebService1Soap.listCourseAsync
            Return MyBase.Channel.listCourseAsync(request)
        End Function
        
        Public Function listCourseAsync() As System.Threading.Tasks.Task(Of ServiceReference1.ListCourse1)
            Dim inValue As ServiceReference1.ListCourse = New ServiceReference1.ListCourse()
            Return CType(Me,ServiceReference1.WebService1Soap).listCourseAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_WebService1Soap_getCourseRegisteredStudents(ByVal request As ServiceReference1.GetCourseRegisteredStudents) As ServiceReference1.GetCourseRegisteredStudents1 Implements ServiceReference1.WebService1Soap.getCourseRegisteredStudents
            Return MyBase.Channel.getCourseRegisteredStudents(request)
        End Function
        
        Public Function getCourseRegisteredStudents(ByVal id As String) As System.Data.DataSet
            Dim inValue As ServiceReference1.GetCourseRegisteredStudents = New ServiceReference1.GetCourseRegisteredStudents()
            inValue.id = id
            Dim retVal As ServiceReference1.GetCourseRegisteredStudents1 = CType(Me,ServiceReference1.WebService1Soap).getCourseRegisteredStudents(inValue)
            Return retVal.GetCourseRegisteredStudentsResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_WebService1Soap_getCourseRegisteredStudentsAsync(ByVal request As ServiceReference1.GetCourseRegisteredStudents) As System.Threading.Tasks.Task(Of ServiceReference1.GetCourseRegisteredStudents1) Implements ServiceReference1.WebService1Soap.getCourseRegisteredStudentsAsync
            Return MyBase.Channel.getCourseRegisteredStudentsAsync(request)
        End Function
        
        Public Function getCourseRegisteredStudentsAsync(ByVal id As String) As System.Threading.Tasks.Task(Of ServiceReference1.GetCourseRegisteredStudents1)
            Dim inValue As ServiceReference1.GetCourseRegisteredStudents = New ServiceReference1.GetCourseRegisteredStudents()
            inValue.id = id
            Return CType(Me,ServiceReference1.WebService1Soap).getCourseRegisteredStudentsAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_WebService1Soap_registerNewCourse(ByVal request As ServiceReference1.Registercourse) As ServiceReference1.Registercourse1 Implements ServiceReference1.WebService1Soap.registerNewCourse
            Return MyBase.Channel.registerNewCourse(request)
        End Function
        
        Public Sub registerNewCourse(ByVal s_id As String, ByVal s_name As String, ByVal c_id As String, ByVal c_title As String, ByVal c_w_hours As String)
            Dim inValue As ServiceReference1.Registercourse = New ServiceReference1.Registercourse()
            inValue.s_id = s_id
            inValue.s_name = s_name
            inValue.c_id = c_id
            inValue.c_title = c_title
            inValue.c_w_hours = c_w_hours
            Dim retVal As ServiceReference1.Registercourse1 = CType(Me,ServiceReference1.WebService1Soap).registerNewCourse(inValue)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_WebService1Soap_registerNewCourseAsync(ByVal request As ServiceReference1.Registercourse) As System.Threading.Tasks.Task(Of ServiceReference1.Registercourse1) Implements ServiceReference1.WebService1Soap.registerNewCourseAsync
            Return MyBase.Channel.registerNewCourseAsync(request)
        End Function
        
        Public Function registerNewCourseAsync(ByVal s_id As String, ByVal s_name As String, ByVal c_id As String, ByVal c_title As String, ByVal c_w_hours As String) As System.Threading.Tasks.Task(Of ServiceReference1.Registercourse1)
            Dim inValue As ServiceReference1.Registercourse = New ServiceReference1.Registercourse()
            inValue.s_id = s_id
            inValue.s_name = s_name
            inValue.c_id = c_id
            inValue.c_title = c_title
            inValue.c_w_hours = c_w_hours
            Return CType(Me,ServiceReference1.WebService1Soap).registerNewCourseAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_WebService1Soap_getAllRegisteredCourses(ByVal request As ServiceReference1.Getallregisteredcourses) As ServiceReference1.Getallregisteredcourses1 Implements ServiceReference1.WebService1Soap.getAllRegisteredCourses
            Return MyBase.Channel.getAllRegisteredCourses(request)
        End Function
        
        Public Function getAllRegisteredCourses(ByVal id As String) As System.Data.DataSet
            Dim inValue As ServiceReference1.Getallregisteredcourses = New ServiceReference1.Getallregisteredcourses()
            inValue.id = id
            Dim retVal As ServiceReference1.Getallregisteredcourses1 = CType(Me,ServiceReference1.WebService1Soap).getAllRegisteredCourses(inValue)
            Return retVal.GetallregisteredcoursesResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_WebService1Soap_getAllRegisteredCoursesAsync(ByVal request As ServiceReference1.Getallregisteredcourses) As System.Threading.Tasks.Task(Of ServiceReference1.Getallregisteredcourses1) Implements ServiceReference1.WebService1Soap.getAllRegisteredCoursesAsync
            Return MyBase.Channel.getAllRegisteredCoursesAsync(request)
        End Function
        
        Public Function getAllRegisteredCoursesAsync(ByVal id As String) As System.Threading.Tasks.Task(Of ServiceReference1.Getallregisteredcourses1)
            Dim inValue As ServiceReference1.Getallregisteredcourses = New ServiceReference1.Getallregisteredcourses()
            inValue.id = id
            Return CType(Me,ServiceReference1.WebService1Soap).getAllRegisteredCoursesAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_WebService1Soap_emailTest(ByVal request As ServiceReference1.emailtest) As ServiceReference1.emailtest1 Implements ServiceReference1.WebService1Soap.emailTest
            Return MyBase.Channel.emailTest(request)
        End Function
        
        Public Function emailTest() As System.Data.DataSet
            Dim inValue As ServiceReference1.emailtest = New ServiceReference1.emailtest()
            Dim retVal As ServiceReference1.emailtest1 = CType(Me,ServiceReference1.WebService1Soap).emailTest(inValue)
            Return retVal.emailtestResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_WebService1Soap_emailTestAsync(ByVal request As ServiceReference1.emailtest) As System.Threading.Tasks.Task(Of ServiceReference1.emailtest1) Implements ServiceReference1.WebService1Soap.emailTestAsync
            Return MyBase.Channel.emailTestAsync(request)
        End Function
        
        Public Function emailTestAsync() As System.Threading.Tasks.Task(Of ServiceReference1.emailtest1)
            Dim inValue As ServiceReference1.emailtest = New ServiceReference1.emailtest()
            Return CType(Me,ServiceReference1.WebService1Soap).emailTestAsync(inValue)
        End Function
    End Class
End Namespace
